### ISSUE TITLE
Unable to compile sha 1b12c63df84ea779e3578db93a7ae140a122acf0 when SSD1305_128_32 defined

### ISSUE THREAD

**Issue by khn** [adafruit/Adafruit_SSD1305#1]
When SSD1305_128_32 is set in the .h file, compiler throws this error.

Adafruit_SSD1305.cpp:114:1: error: too many initializers for 'uint8_t [512] {aka unsigned char [512]}'
 };

Will compile if line 80 is moved below "#if (SSD1305_LCDHEIGHT == 64)" (line 81)

**Comment by caternuson** [comment]
Looks like there are multiple issues going on for the 128x32 display. Closing this issue so we can consolidate efforts in #12.
