### ISSUE TITLE
Display output seems to be shifted down and to the left by 4 pixels

### ISSUE THREAD

**Issue by ghassanoueidat** [adafruit/Adafruit_SSD1305#10]
So after fixing the buffer definition for the 128 x 32 display and correcting line 189 in Adafruit_SSD1305.cpp, the display "seems" to work properly. However, the output is being shifted 4 pixels to the left and 4 pixels down. I'm currently going through the library, if i manage to find what is causing this i'll post a followup, if someone else had the same problem and was able to fix it, time is of the essence... 

P.S. The problem might not even be from the library itself but statistically speaking given that it contains the other issues mentioned (buffer size and static screen), i'm starting there.

**Comment by ghassanoueidat** [comment]
According to the SSD1305 datasheet, it is possible to shift the display in the vertical direction in command table 9-1 "Set vertical shift by COM from 0~63.The value is reset to 00h after RESET." on page 35. 
Unfortunately i couldn't find any offsetting in the horizontal direction and adding a scrolling to the right function isn't the way to go. 

Going back to the datasheet there is the Set Segment Re-map on page 34:
 "X[0]=0b: column address 0 is mapped to SEG0 (RESET)
X[0]=1b: column address 131 is mapped to SEG0"

This is simply a mirroring command, what's interesting here is that there are 132 elements instead of 128 which tells me that there might be a solution through addressing (not sure though). However, setting SSD1305_SEGREMAP in the .h file to 0xA1 or by  changing the .cpp at the initialization sequence the command(SSD1305_SEGREMAP | 0x01) to command(SSD1305_SEGREMAP | 0x00), does solve the shifted pixels issue but opens up the door to a problem of mirroring back the output of the last 128 column addresses instead of the 132 columns.

Even though 132 columns does not make any sense since the display only contains 128, the 132 column addresses come from the fact that the SSD1305 can support up to 132 columns and so for some reason the first pixel column is connected to the 4th address.

I won'd go deeper into this, but the solution to this problem isn't by playing with the Set Segment Re-map command, it can be solved in two ways:

1- hardware modification to the breakout (highly not recommended)
2- target the 4th column address as your first column, and this can be done with a simple function sitting in whatever editor you're using.

Again if anyone passes by this in the future and knows the solution to this annoying problem, please do share it.

**Comment by afefer** [comment]
@ladyada - just noticed you made some recent commits to fix issues related to the 128x32 OLED display, but this one seems to be there in the latest build.  See image attached for text written at cursor (0,0) - there's a 4-column and 4-row offset as described above. Also note that the clearDisplay() function does not clear the entire buffer (there are three columns of random pixels that persist on the right side of the screen).

Is this a known issue / is there any workaround for this one?

![oled_problem](https://user-images.githubusercontent.com/3399494/82772124-17322f00-9df3-11ea-82bb-5f46c6b17e9e.jpg)

**Comment by ladyada** [comment]
what adafruit product id is that?

**Comment by afefer** [comment]
> what adafruit product id is that?

@ladyada - it’s 2675. 
https://www.adafruit.com/product/2675

**Comment by ladyada** [comment]
kk we can take a look at it, probably just needs the column offset adjusted

**Comment by afefer** [comment]
Thanks! I believe it’s shifted down, so there’s a row offset as well.

**Comment by afefer** [comment]
Thanks @ladyada. I noticed the column offset variable in Adafruit_SSD1305.h, but it doesn't actually appear to be used anywhere in the code.

**Comment by afefer** [comment]
Thanks @ladyada. I noticed the column offset variable in Adafruit_SSD1305.h, but it doesn't actually appear to be used anywhere in the code.

**Comment by afefer** [comment]
I was hacking around with Adafruit_SSD1305.cpp and adding in the column offset to the lines below in Adafruit_SSD1305::display() appears to have resolved the issue, at least on this panel (with the column offset in AdaFruit_SSD1305.h set to -4). @ladyada, since you wrote the original code and this has to work with other panels, I'll defer to you on whether this is a robust solution or I've missed something:

<pre><code>
ptr = buffer + (uint16_t)p * (uint16_t)bytes_per_page <b>+ column_offset</b>;
    // fast forward to dirty rectangle beginning
    ptr += page_start;
    bytes_remaining -= page_start + <b>column_offset</b>;
</code></pre>

Also disregard my comment above on there being a 4-row offset - it seems as though the usable pixels aren't vertically centered within the bezel, so there's an asymmetrical gap.

**Comment by ladyada** [comment]
thanks, can you submit a PR? i have not gotten an oled to test with yet :)

**Comment by caternuson** [comment]
related:
https://forums.adafruit.com/viewtopic.php?f=47&t=165677#p814903

**Comment by afefer** [comment]
Oops - sorry about the delay on this. @ladyada I'll submit a PR shortly.

**Comment by caternuson** [comment]
I'm curious - what necessitates this offset for the 128x32 configuration?
https://github.com/adafruit/Adafruit_SSD1305/blob/f0666c82a895a106c8b8b40be386756f8fe1cdba/Adafruit_SSD1305.cpp#L227

**Comment by drewmutt** [comment]
Bump. Had the same issue with my OLED:
https://www.waveshare.com/wiki/2.23inch_OLED_HAT

Messed with the initialization settings, to no avail (which makes me think they only incidentally work because they're all post-reset defaults). Anywho, the column offset mentioned by @afefer worked for me.

**Comment by ladyada** [comment]
added col offset, should be good!
