### ISSUE TITLE
SSD1305 128x32 Not Working Properly with Feather M0 based Board over I2C

### ISSUE THREAD

**Issue by nunomiguelferreira** [adafruit/Adafruit_SSD1305#14]
- Arduino board:  Custom Board Based on Feather M0

- Arduino IDE version (found in Arduino -> About Arduino menu):  1.8.9

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): 

Run Example SSD1305 with the line for the 128x32 pixel display uncommented.

Hello. Forwarding some issues other people have had with this library for the 128x32 display, it seems I can't get it working properly, even after updating to the 1.0.3 release of December which should fix most of these issues. I dropped a pic below to show what happens. It is connected via I2C, with a pullup on the reset pin.

![S1305](https://user-images.githubusercontent.com/33719583/77939600-550d4e00-72af-11ea-9236-3431488fee0f.jpeg)
![SSD1305](https://user-images.githubusercontent.com/33719583/77939603-563e7b00-72af-11ea-9e38-30e72bf1c5f9.jpeg)

**Comment by ladyada** [comment]
hi you are probably missing pullups on I2C, this library has been re-factored and was tested on a M4
