### ISSUE TITLE
Compile library for Linux-based system

### ISSUE THREAD

**Issue by ricbrue** [adafruit/Adafruit_SSD1305#18]
I need to use this display controller library on a Linux-based system (where there are the "i2c-dev.h" and "smbus.h" libraries). Is it possible to port this library in such system? If so I'll start the porting, otherwise what do you suggest me to? I cannot find any other library for such controller.

**Comment by ladyada** [comment]
hihi - linux is not supported here. you can look for other libraries that could add it, we wouldn't add support for linux on an arduino library. we have python here https://github.com/adafruit/Adafruit_CircuitPython_SSD1305
