### ISSUE TITLE
Missing documentation of SPI connection of Adafruit 2.23" Monochrome OLED Bonnet

### ISSUE THREAD

**Issue by Sentinel8000** [adafruit/Adafruit_SSD1305#28]
Now i got the adatfruit version of this display, this looks have L2C connection (default?), but example and the library looks using SPI connection default, not realy clear this display have now both SPI and l2C connection, just need use different pins and/or if have SPI what is the pins what need use to make work this library with SPI.

The Waveshare version have default SPI mode and dedicated SPI pins working well using SPI, but adatfruit version have just a hat conenctor and descrition talking only about l2c.

**Comment by ladyada** [comment]
if you're referring to 
https://www.adafruit.com/product/4567
please read the guide here
https://learn.adafruit.com/adafruit-2-23-monochrome-oled-bonnet
this is the arduino library, not for raspberry pi users

**Comment by Sentinel8000** [comment]
Yeah, i have read all of these and the question is still remains, because im using this with arduino, not with raspberry. 

You have not included too much documentation about your library.  

However thanks for all of your helps, you are a realy friendly:)

**Comment by ladyada** [comment]
hiya, the hat isn't really designed for use with arduino, but you should be able to use i2c support to talk to the OLED

questions about how to use adafruit products are best posted in the adafruit forums  at [forums.adafruit.com](forums.adafruit.com/)
thats where tech support is handled - github issues are where folks can issue bug reports (e.g. something that ought to work but doesnt due to a hardware or software bug)

thanks! :)

**Comment by Sentinel8000** [comment]
Im little bit confused, you say this OLED not realy designed for arduino, but you inserted same OLED photo in the library:> 

Without any readme for a user not clear what is compatible with this library. Also github have no feature for asking question from the creator.

This ssd1305 display working well with L2C/arduino also with esp32 too, just need put 4 wire in the hat connector. After i saw your included photo about the OLED and in the example code the SPI connection, i dont know how is possible. Adatfruit documentaion with python examples have no sense, real specification missing.

Also i have found a bug or maybe this is just again a compatibility problem - as you know i have two ssd1305 OLED,s one from adatfruit one from waveshare. Waveshare looks have SPI, adatfruit looks have L2C connection.

Waveshare OLED making weird effect: sometimes if my project freeze - during testing - on OLED screen display will be visible weird points, lines, board need restart. But vertical lines remains on display after restart and also display.displayclear not removing these lines after restart. If im upload waveshare example+waveshare ssd1305 library, screen will be realy cleared to black.

But sorry, you have right - because i have used ,,illegaly" without reason issue report and lookslike i have just ,,non" supported 2x ssd1305 OLEDs.

thanks for your time

**Comment by ladyada** [comment]
we've updated the image, its now the correct item
