### ISSUE TITLE
Undefined setBrightness method

### ISSUE THREAD

**Issue by watchinofoye** [adafruit/Adafruit_SSD1305#8]
Hello.

I've just figured out setBrightness method is declared in Adafruit_SSD1305 class but is never implemented. It does not seem it's a virtual method nor inherited method, so I wonder if it's destined to be declared or if it's an old method which declaration have been let by mistake.

In any case, it should be corrected by removing declaration of setBrightness or by implementing the method.

Thanks in advance.

**Comment by ladyada** [comment]
this library has been re-factored and now has setContrast()
